alto = float(input())
ancho = float(input())
profundo =  float(input())
volumen = float(alto*ancho*profundo)
costoFinal = float(volumen*5)
print(alto)
print(ancho)
print(profundo)
print(volumen)
print(costoFinal)
